apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: fuse-brms-service
    name: fuse-brms-service
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: fuse-brms-service
    name: fuse-brms-service
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: fuse-brms-service:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: http://gogs-cicd.192.168.42.19.nip.io/gogs/fuse-brms-service.git
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: MAVEN_MIRROR_URL
          value: https://10.10.com
        from:
          kind: ImageStreamTag
          name: fis-java-openshift:latest
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: 8-Fgq0fX-8yw67IpdK1x
      type: GitHub
    - generic:
        secret: 9NW-jyEI6U3np1UC4DkI
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: fuse-brms-service
    name: fuse-brms-service
  spec:
    replicas: 1
    selector:
      app: fuse-brms-service
      deploymentconfig: fuse-brms-service
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: fuse-brms-service
          deploymentconfig: fuse-brms-service
      spec:
        containers:
        - image: fuse-brms-service:latest
          name: fuse-brms-service
          ports:
          - containerPort: 8778
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - fuse-brms-service
        from:
          kind: ImageStreamTag
          name: fuse-brms-service:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: fuse-brms-service
    name: fuse-brms-service
  spec:
    ports:
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      app: fuse-brms-service
      deploymentconfig: fuse-brms-service
  status:
    loadBalancer: {}
kind: List
metadata: {}
